<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>ba003e96-78d9-4971-a1fd-ace0f347d548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fecha-profile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fecha-profile > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3df0fb36-df1b-4f70-9242-08f7f2324bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png</value>
      <webElementGuid>d7fa52fc-82c4-46b6-a8d8-e87a56de075f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>12bfbb39-41a3-477e-a024-bb5e982cb615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>c47dbc51-9d01-461b-9ff1-efcd678f5304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha-profile&quot;)/img[1]</value>
      <webElementGuid>e9b6131e-e3bf-43b2-9b35-7d8032f03e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fecha-profile']/img</value>
      <webElementGuid>cea8ad7c-82ad-4df1-afa0-2ead02c8dbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png')]</value>
      <webElementGuid>802b4805-64f9-4a16-92f6-7ae2ed43571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>f1a62bbf-4d91-4d24-906e-0f5195d5c949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png']</value>
      <webElementGuid>c1cdd172-5878-480d-a342-8866ebe873ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
