<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Autoestudio</name>
   <tag></tag>
   <elementGuidId>cb47b20c-65bc-47b5-a125-6dc01040d3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.item-388.deeper.parent > a.separator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44794c33-aaca-457b-9704-da78fbb22e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>d43eefd2-a14a-4dbb-9d28-d4f36eb59692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.4051133046381745</value>
      <webElementGuid>5c819106-33da-4cc0-b42f-521d58247f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autoestudio</value>
      <webElementGuid>189cc204-7543-46b9-8862-aacfcd9f1fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-388 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>ec1ae449-7b6c-4a60-9ca7-e0b93967a449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[3]/a</value>
      <webElementGuid>07aae515-a0fe-4ef8-a03e-ca51e9e29ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Autoestudio')]</value>
      <webElementGuid>d4004302-23d7-43bb-bc0e-779d0ebc4793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inducción GMM'])[1]/following::a[1]</value>
      <webElementGuid>0581e831-d222-4045-8d5a-15370b3d4ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inducción a GNP'])[1]/following::a[2]</value>
      <webElementGuid>86ebe26a-7b28-44c6-92ea-24923fdb2b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microclases'])[1]/preceding::a[1]</value>
      <webElementGuid>4cfbd6b2-052c-47e7-b626-301228708d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS en Corto'])[1]/preceding::a[2]</value>
      <webElementGuid>e1fa4f22-cd7f-4921-9cc7-09ea4fbfdd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autoestudio']/parent::*</value>
      <webElementGuid>5fda7a51-9baa-47b9-9fc5-ee5f01783191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.4051133046381745')]</value>
      <webElementGuid>b4dabcc3-6e02-49a3-a975-6059b5266ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>d07d3c2e-5cd0-4e13-a50d-8bf37779a00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.4051133046381745' and (text() = 'Autoestudio' or . = 'Autoestudio')]</value>
      <webElementGuid>996489a7-b1aa-49c0-bb5b-6d47f2065e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
