<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Aprende</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8b7e1f81-3789-4748-af49-3a4b45b8f034</testSuiteGuid>
   <testCaseLink>
      <guid>2ad4f855-f72f-4775-8743-38d096c8980a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Plan de Carrera</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c14ea92e-0928-452b-b589-d79194a0a2bf</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c14ea92e-0928-452b-b589-d79194a0a2bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>0f833462-87b6-46c5-a43d-64bacfc93cca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c14ea92e-0928-452b-b589-d79194a0a2bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>40c47675-f442-40d8-a558-11a5fe1ab005</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
