<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Aprende</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8b7e1f81-3789-4748-af49-3a4b45b8f034</testSuiteGuid>
   <testCaseLink>
      <guid>d23ccc60-7550-4c92-bace-a7d9966db82b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reclutamiento</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>967abb6f-65d6-4203-98c3-eb4269657c0a</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2,3,4</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>967abb6f-65d6-4203-98c3-eb4269657c0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>033ab877-8dbc-4652-9ce3-fb5adae9b7fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>967abb6f-65d6-4203-98c3-eb4269657c0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>663431c3-8fa6-4f83-a38a-11d98f007b5a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
