<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TemaHerramientasEstructura Comercial_04129c</name>
   <tag></tag>
   <elementGuidId>17b4cbe5-e3b6-48b0-8032-7b4e68d93af9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='categorysel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;categorysel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d1aca76-650f-4bd7-aea8-2393807e176c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categorysel</value>
      <webElementGuid>b6a4b235-1ffe-4a91-a46c-008e5d300bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>8ef6525e-cd05-48e3-9456-f940abd0036c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TemaHerramientasEstructura ComercialInformación GeneralAgenda estas FechasCapacitación</value>
      <webElementGuid>6273aa50-ab14-4c2b-9bd6-89f700ab76a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-category&quot;)/select[1]</value>
      <webElementGuid>1fe1c280-9155-420a-ad1e-889f70688d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='categorysel']</value>
      <webElementGuid>5a4cec1d-d7d8-4db8-817b-b3d6d7c393f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-category']/select</value>
      <webElementGuid>36ca73bb-5592-4a00-9396-b1b9603f7b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas Informativas'])[3]/following::select[1]</value>
      <webElementGuid>d931dc32-8a23-41cf-a55f-2436b0b345c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas Informativas'])[2]/following::select[1]</value>
      <webElementGuid>a2fd430b-7e03-4753-9b18-2ab460b6f7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>67716bbb-d7fb-40dd-871d-ad316f00aa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'categorysel' and (text() = 'TemaHerramientasEstructura ComercialInformación GeneralAgenda estas FechasCapacitación' or . = 'TemaHerramientasEstructura ComercialInformación GeneralAgenda estas FechasCapacitación')]</value>
      <webElementGuid>79528c1d-d4e0-461b-82d4-9df2a350ad66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
