<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>45f3fbee-58e5-4436-8065-2551a65f1532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fecha-profile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fecha-profile > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6223b7c2-226c-45e8-967c-471cd670bbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png</value>
      <webElementGuid>b0a21e99-b524-46df-968e-e80e9ba8e3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>c22ea63f-90d2-4db1-8f53-3db2eac438cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>fe4cb442-e7a7-453d-a8c1-7e12948c11c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha-profile&quot;)/img[1]</value>
      <webElementGuid>86278cba-367e-4014-b4e5-d4c10245721a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fecha-profile']/img</value>
      <webElementGuid>6f67c0de-3915-4eb6-a7c4-3d0c26a0bbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png')]</value>
      <webElementGuid>2a6a47d9-3c0d-4fd6-8755-55289cc040bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/img</value>
      <webElementGuid>867a9db1-0cac-40be-8e5b-749a0a5b9621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png']</value>
      <webElementGuid>a2d03b34-2ddb-4296-83f5-741fb85d7f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
