<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quines somos</name>
   <tag></tag>
   <elementGuidId>0c40a66b-d44e-4fce-bf5a-3d563591470b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titulo-articulos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo-articulos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6605f3d-b13f-4c0a-9e8f-ced82949078f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo-articulos</value>
      <webElementGuid>b7044676-4bd0-458d-9803-ab333804f470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¿Quiénes somos?</value>
      <webElementGuid>c70a4d43-ec41-42c5-8bef-ea85311ef0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo-articulos&quot;)</value>
      <webElementGuid>3cef8817-44dc-4dc6-9ae2-8b961ab25e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo-articulos']</value>
      <webElementGuid>e76512ae-b440-48dd-8c28-ecdad5afac1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros-articulos']/div</value>
      <webElementGuid>2e8826c6-fbfa-4c17-b7fc-5ea027e08d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[2]/following::div[10]</value>
      <webElementGuid>8dfd88f6-868d-463c-9bc7-b8246c14105d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oferta Educativa'])[2]/following::div[10]</value>
      <webElementGuid>02b350d5-b1dd-4e9e-bb51-428b44471ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[3]/preceding::div[1]</value>
      <webElementGuid>8c56fd4d-f2f8-4034-8e45-dff7758a7a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¿Quiénes somos?']/parent::*</value>
      <webElementGuid>3e6e8c3b-e94c-4a65-aa89-732d047409a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/article/div/div</value>
      <webElementGuid>d0858735-0869-412b-9c67-438acfd2d006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo-articulos' and (text() = '¿Quiénes somos?' or . = '¿Quiénes somos?')]</value>
      <webElementGuid>84532fde-0bad-4226-8854-b03a974ba992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
