<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reglamento</name>
   <tag></tag>
   <elementGuidId>be7e4d67-e98d-432a-aac9-58391d66f039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.item-1005 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccc1ae6b-a5d8-4b15-a2cf-bda99716b708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/oferta-educativa/reglamento?rand=0.36183979358983476</value>
      <webElementGuid>b8ef0cb6-444c-4b18-b48f-274767173cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reglamento</value>
      <webElementGuid>900ac11e-c80d-4e66-ad42-af01bc7b33bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-376 deeper parent&quot;]/ul[1]/li[@class=&quot;item-1005&quot;]/a[1]</value>
      <webElementGuid>5a42a9b4-b5c7-4c2d-a820-76e2a20eddcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li/ul/li[4]/a</value>
      <webElementGuid>2ace5f4c-20dc-448d-9346-1bbf9d63f4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reglamento')]</value>
      <webElementGuid>1def37f1-571c-4fac-89e5-aca34f92f451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros PyMEs'])[1]/following::a[1]</value>
      <webElementGuid>7f59d604-918f-4746-808a-77ee9cfb03bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros de Personas'])[1]/following::a[2]</value>
      <webElementGuid>17d0bdad-c5d3-4daf-b2ed-120e69467b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mi Plan de Carrera'])[1]/preceding::a[1]</value>
      <webElementGuid>e3edda91-d88a-4ec9-aac5-15896eed9747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Avances'])[1]/preceding::a[2]</value>
      <webElementGuid>5c3b715e-c078-46ab-8b84-a2a75e9a3c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reglamento']/parent::*</value>
      <webElementGuid>dafb3cad-fcb9-4c74-9c08-35dee9728fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/oferta-educativa/reglamento?rand=0.36183979358983476')]</value>
      <webElementGuid>f78d5693-c747-461d-94ef-5658c58cc143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a</value>
      <webElementGuid>85dbd35b-888a-4121-80dc-19da67aca6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/oferta-educativa/reglamento?rand=0.36183979358983476' and (text() = 'Reglamento' or . = 'Reglamento')]</value>
      <webElementGuid>2994d623-04be-4a70-b7d8-e9666f54f1f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
