<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Infrmate_svg</name>
   <tag></tag>
   <elementGuidId>1d041a76-4234-4c78-86df-d938ac8794f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/div[2]/div[2]/div/div/article/div/div/table[2]/tbody/tr/td[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3b45da6-9b6c-4e67-b7c0-bc8e6883e43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>92bd760a-0cd8-4328-9a3e-80a54b672ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/images/GuiasPortal/Guia-Ideas_2021_Agentes.pdf</value>
      <webElementGuid>7af12c72-a0b9-4d3c-8fdc-11af1c82dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/div[@class=&quot;art-sheet clearfix&quot;]/div[@class=&quot;art-content-layout&quot;]/div[@class=&quot;art-content-layout-row&quot;]/div[@class=&quot;art-layout-cell&quot;]/article[@class=&quot;art-post&quot;]/div[@class=&quot;art-postcontent clearfix&quot;]/div[@class=&quot;custom&quot;]/table[@class=&quot;tbl_aprende_informate_1&quot;]/tbody[1]/tr[1]/td[6]/a[@class=&quot;svg&quot;]</value>
      <webElementGuid>82354924-f2ed-448c-8de6-8471cde1a779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/div[2]/div[2]/div/div/article/div/div/table[2]/tbody/tr/td[6]/a</value>
      <webElementGuid>e698d692-ca69-4ffc-977c-447e431eace5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infórmate'])[1]/following::a[5]</value>
      <webElementGuid>b134016c-4245-486d-ba99-de16ed8ebcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aprende'])[1]/following::a[10]</value>
      <webElementGuid>1cff7213-5110-4424-a16f-a4150a4c4b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviso de privacidad'])[1]/preceding::a[5]</value>
      <webElementGuid>4eb77c73-3740-49a1-baf8-16c59c8ae176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/images/GuiasPortal/Guia-Ideas_2021_Agentes.pdf')]</value>
      <webElementGuid>9f929db3-1f0b-4d58-8f85-0140535b2d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[6]/a</value>
      <webElementGuid>7884b309-102e-406d-8e44-dbeae841acbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/images/GuiasPortal/Guia-Ideas_2021_Agentes.pdf']</value>
      <webElementGuid>0330b3ce-25b0-46c5-b4f1-f57bbb4fe837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
