<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Arranque</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bb7231e8-ca97-4b8d-a7df-4c21c092fcf9</testSuiteGuid>
   <testCaseLink>
      <guid>c3111811-1048-4834-80ed-aa0869ee11a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atracción y Desarrollo/Arranque</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1404ad89-6562-4c75-b7ce-8af742f35ded</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>4,2</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1404ad89-6562-4c75-b7ce-8af742f35ded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>9b870e18-d13f-4134-b9e4-cf5d5c57132b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1404ad89-6562-4c75-b7ce-8af742f35ded</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>e56520fc-93c2-455f-a2ef-963e123cb27e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f446d09-db62-4fe1-97b4-27a982a33fd9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/En contacto contigo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844440bc-3efe-4be3-9999-d6875cd159a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0fb9fd2-db09-41ea-bc01-caecc37e6216</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
