<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Artículos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ef6369c9-25fb-4576-8a81-1079b3303918</testSuiteGuid>
   <testCaseLink>
      <guid>3fb4d235-c4d4-4786-a0ff-f4d2add01e12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Artículos</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8b56859d-ed04-4377-80ce-cf0a78d8c5c0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8b56859d-ed04-4377-80ce-cf0a78d8c5c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>4cd5ab44-c588-4bc7-ab97-c50b225c219f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8b56859d-ed04-4377-80ce-cf0a78d8c5c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>37c70c40-cc5e-4c42-86ca-8ba67bc589d2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
