<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Campañas</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5ee29e27-dc64-44d6-8ff8-b657922ab5aa</testSuiteGuid>
   <testCaseLink>
      <guid>1769cb26-1923-4cdf-a47c-1b0351faa845</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Informate/Campañas</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b6610a13-da1a-45d3-afe3-39ebfb8d8bc2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b6610a13-da1a-45d3-afe3-39ebfb8d8bc2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>e442cfc5-b6bb-4929-a775-588b04bcba98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b6610a13-da1a-45d3-afe3-39ebfb8d8bc2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>32a1b483-3884-47a5-89be-b5a5ae075647</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
