<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Circulares</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>49258c9c-2dc7-49d8-a179-11c6fa42ea8e</testSuiteGuid>
   <testCaseLink>
      <guid>71c589d5-2343-4bf0-addc-0999936800af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Informate/Circulares (informate)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c2e98015-d69f-4d23-acaf-922a21af3291</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c2e98015-d69f-4d23-acaf-922a21af3291</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>fd11a263-0f15-4342-ae02-9d51412ab142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2e98015-d69f-4d23-acaf-922a21af3291</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>88ed1659-f409-46bc-b7e5-a42f1ceb8b10</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
