<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Eventos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>27304242-f18f-40ee-9ea4-13ae6d5e0018</testSuiteGuid>
   <testCaseLink>
      <guid>80360197-166b-42ef-926a-3d99aa6de39c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/Eventos</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>45b69948-5e2b-449f-af0e-008f4ec499e8</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,2,3,15,16</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7daf71d4-4fc9-49f1-8481-575181196c57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>488aa7be-1da4-49f7-894f-130310b976ec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
