<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Libros</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>80417a0d-366f-4aaa-95f1-b6746c0671b7</testSuiteGuid>
   <testCaseLink>
      <guid>d7d9bbb3-ee56-43fd-8f11-8ea27ebbc75a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Aprende/Libros</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>51e7499f-60df-4e47-ab4b-d8533512bc2c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>51e7499f-60df-4e47-ab4b-d8533512bc2c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>7638d1e7-c7e1-456f-bd7e-d4887c95531b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>51e7499f-60df-4e47-ab4b-d8533512bc2c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>c06d2f14-a627-4512-a7f1-fdf375efc2f2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
