<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Microclases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3221f999-63ae-4dd7-b25b-aec0f61ed5f6</testSuiteGuid>
   <testCaseLink>
      <guid>ac885f91-fc7a-4f19-bdd7-a9073696d0ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Autoestudio/Microclases</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1d2f16f0-c73c-432b-b317-bfe64c7670b7</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1d2f16f0-c73c-432b-b317-bfe64c7670b7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>f5ed0c89-de4c-4af2-b62e-a9c4debf6a9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1d2f16f0-c73c-432b-b317-bfe64c7670b7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>e0873c31-66ca-47be-95b2-bba3f24e2e75</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
