<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prueba_EnCanalContigo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e71d1819-5e13-4637-ae0f-eecc16c7c7e2</testSuiteGuid>
   <testCaseLink>
      <guid>41e93481-3b9c-42f1-b72c-679fee023663</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Prueba_EnCanalContigo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2374a001-4fca-4b87-a275-fad9a37e0486</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2374a001-4fca-4b87-a275-fad9a37e0486</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>c8e923b6-b8b4-474f-9ed9-6ec3ad989830</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2374a001-4fca-4b87-a275-fad9a37e0486</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>0fef8d7d-d398-4936-8623-bc80a226e90c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
