<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prueba_Autoestudio_CedulaA2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>078b2749-9240-43dd-92f5-f753a3c8d596</testSuiteGuid>
   <testCaseLink>
      <guid>5b6e09ed-d2bd-45e5-8450-15bdd7f9ba75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Prueba_Autoestudio_CedulaA2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b4debf1a-e810-495b-9e1b-7c9f43358251</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2,5</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea4780da-d4b2-4ff4-9448-f6be45ec5954</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c613ed1-795d-4e11-91b0-34f6149c7e56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
