<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Reclutamiento</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>103b5621-706a-4be1-83b1-9d329114ed65</testSuiteGuid>
   <testCaseLink>
      <guid>08c8b477-33d5-4fa8-84e8-bf3870b045b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atracción y Desarrollo/Reclutamiento</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d7cfa342-e8da-43bc-a227-dba6dbaee5a1</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,4</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d7cfa342-e8da-43bc-a227-dba6dbaee5a1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>033ab877-8dbc-4652-9ce3-fb5adae9b7fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d7cfa342-e8da-43bc-a227-dba6dbaee5a1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>663431c3-8fa6-4f83-a38a-11d98f007b5a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
