<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Reglamento</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>32461d9e-fb7f-4a59-9a8c-1e05efb61bbe</testSuiteGuid>
   <testCaseLink>
      <guid>6ce8a3cb-ecfe-41f0-a84c-7199eb807ce9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reglamento</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e73da2f8-b123-4bca-a6cb-f193ae810802</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e73da2f8-b123-4bca-a6cb-f193ae810802</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>cc56e211-d59b-4476-a293-cf2769a6d4ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e73da2f8-b123-4bca-a6cb-f193ae810802</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>3c0d08e5-d4d7-4376-bb9f-874069803722</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
