<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Vídeos</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>452beafc-e20c-4e8b-a570-f151aa3e5699</testSuiteGuid>
   <testCaseLink>
      <guid>71127631-b389-463d-afff-29bca82f7586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Vídeos</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d0ff4c70-5499-4ef4-8eb9-3c84f9a5c665</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d0ff4c70-5499-4ef4-8eb9-3c84f9a5c665</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>32a8022c-a11b-42d8-98f2-f685b5f46c92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0ff4c70-5499-4ef4-8eb9-3c84f9a5c665</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>1ea51084-ca9f-4db8-b482-1d9cca40f1a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
