<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_15  julio  2022</name>
   <tag></tag>
   <elementGuidId>0e342f6b-76e2-4e0a-a458-df6f7b4f992c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fecha-profile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fecha-profile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efefd1dc-aa06-4b86-960f-67c13c353d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fecha-profile</value>
      <webElementGuid>ed1b4256-92b2-4bb4-8410-03c5d49e4c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		15 / julio / 2022	</value>
      <webElementGuid>e7f6cfe8-f509-437a-92cc-9c546cc1d3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha-profile&quot;)</value>
      <webElementGuid>3e59742f-1da4-4ac3-8aab-dc228de14fb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fecha-profile']</value>
      <webElementGuid>ef039bf3-bf58-463c-8c94-8e00ba32b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[3]</value>
      <webElementGuid>f5d3d62c-5cf5-42bb-b7d5-302423e1e8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Agente - biaani.agentec'])[1]/following::div[1]</value>
      <webElementGuid>ffe6f6ca-bcfc-46ce-99d5-aa22ad289463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Bienvenido!'])[1]/following::div[1]</value>
      <webElementGuid>2d2e71e8-0f92-49d4-88b5-c25bdf4eb6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curso'])[1]/preceding::div[1]</value>
      <webElementGuid>c7012b33-1ad6-4e74-bb19-ed5ac47a44ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Learning'])[1]/preceding::div[1]</value>
      <webElementGuid>5c926655-efc0-4442-91cb-3435741c8023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15 / julio / 2022']/parent::*</value>
      <webElementGuid>f6cbffdb-7b4e-4f44-a33a-e6a230c2b8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>357f7737-15ea-49d6-b60c-a2b39a536791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fecha-profile' and (text() = '
		15 / julio / 2022	' or . = '
		15 / julio / 2022	')]</value>
      <webElementGuid>ca5942cb-f14c-4388-9148-19d709b1740a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
