<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Oferta Educativa</name>
   <tag></tag>
   <elementGuidId>ec24b357-cfb6-4d9e-b2c8-969994925b27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.separator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71d92abb-90f9-4137-9aeb-9f89bceac004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>04582184-53e8-40ca-a630-f1e384a6664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.13539746251701557</value>
      <webElementGuid>0d26c0b0-e6a9-461c-b74b-2dd926edfd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oferta Educativa</value>
      <webElementGuid>421ec29c-4003-47eb-85bb-ffafd09e7dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-376 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>163d7ca5-b1b9-4748-bd65-6425be04b1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      <webElementGuid>77365b60-c1da-44a5-8883-e44e201de6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Oferta Educativa')]</value>
      <webElementGuid>ba58ac5e-3342-4589-bc03-155b24799585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::a[2]</value>
      <webElementGuid>fc672dc5-2dc9-4e00-87c0-88285da5174c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Agente'])[1]/following::a[3]</value>
      <webElementGuid>de2e4e5f-e284-4bd7-b3b9-1c45a8964995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[1]/preceding::a[1]</value>
      <webElementGuid>e9831d60-9e4b-4665-b1a3-53eaa276d407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros de Personas'])[1]/preceding::a[2]</value>
      <webElementGuid>37ed518c-b455-4071-9e32-d217897c0586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oferta Educativa']/parent::*</value>
      <webElementGuid>9af5334a-6aa0-432e-8e6a-1101957a1e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.13539746251701557')]</value>
      <webElementGuid>1c0ddfcc-6d78-4d0e-a7ba-8c12ef349248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>7303d9e5-b344-4409-a584-fd04dca1aead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.13539746251701557' and (text() = 'Oferta Educativa' or . = 'Oferta Educativa')]</value>
      <webElementGuid>ad4eb6d7-fecb-4dd4-8318-92e7e5ec0106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
