<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bsico</name>
   <tag></tag>
   <elementGuidId>2ac2344e-fded-4da5-a09e-0249237ff12b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-first-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-first-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff8b0b9f-e0fa-4f32-8a69-1e72203deca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-first-1</value>
      <webElementGuid>22051cf0-9691-4f98-979d-5e7956d904d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Básico
            </value>
      <webElementGuid>52986a00-d9b2-422a-8512-24f7ca4c1bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-first-1&quot;)</value>
      <webElementGuid>430b28b2-f2d8-46ae-b73d-3e46a5affd76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='header-first-1']</value>
      <webElementGuid>07cfbae8-4200-4917-94ee-f0c5489ebe95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-table']/div[2]</value>
      <webElementGuid>ab9bb07f-0f41-4dac-bed7-0770f3634b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programa'])[1]/following::div[1]</value>
      <webElementGuid>7cec0731-341d-41f0-910c-f8867fe45339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros PyMEs'])[2]/following::div[6]</value>
      <webElementGuid>40418155-3594-4913-b0fd-b0f80a9d85c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermedio'])[1]/preceding::div[1]</value>
      <webElementGuid>e3f8eec2-5096-4c2c-9804-5930597aa4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avanzado'])[1]/preceding::div[2]</value>
      <webElementGuid>fc79c136-db6f-4a60-9714-dd278123852f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Básico']/parent::*</value>
      <webElementGuid>2be88d65-1ddd-4a83-b2d8-cdc6329b28c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>0532a2ab-3e19-4f0a-a35e-a6c8f9ac714c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'header-first-1' and (text() = '
                Básico
            ' or . = '
                Básico
            ')]</value>
      <webElementGuid>dd834d35-9ac8-48d1-abd6-44a38e85fa7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
