<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Artculos</name>
   <tag></tag>
   <elementGuidId>41f6c75e-5964-4c72-b270-d7882f8a41e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[4]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.item-398 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd6e0027-7c95-424b-ae85-9a992fab9936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/material-de-apoyo/artículos?rand=0.6914370415281099</value>
      <webElementGuid>969c7f6c-cae5-48d1-ab4b-4b73939cdd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artículos</value>
      <webElementGuid>f9d7e313-2531-44e1-ac3b-3b7e20e3428b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-397 deeper parent&quot;]/ul[1]/li[@class=&quot;item-398&quot;]/a[1]</value>
      <webElementGuid>d6bdf6de-85e0-4bc4-a5c6-e0fdb1504ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[4]/ul/li/a</value>
      <webElementGuid>3d03abc0-44f6-411a-afce-4bea431b39a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Artículos')]</value>
      <webElementGuid>7dadf5aa-1ecb-4ffd-89cf-3f03c3ff7f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[1]/following::a[1]</value>
      <webElementGuid>12f4c236-cc70-463b-aea1-368b73ff63a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cédula B'])[1]/following::a[2]</value>
      <webElementGuid>9bb0fdb6-c585-409d-a726-1450acb6f021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[1]/preceding::a[1]</value>
      <webElementGuid>999499b1-db17-4c24-b8f1-0d3d95a91484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tips de Venta'])[1]/preceding::a[2]</value>
      <webElementGuid>aa2d4634-0b34-4b20-ba8c-60154604a7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Artículos']/parent::*</value>
      <webElementGuid>43f44a90-ed48-4cd4-b08b-f4254b072258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/material-de-apoyo/artículos?rand=0.6914370415281099')]</value>
      <webElementGuid>ec32dadc-4845-4f6a-93f0-13feae9dbfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>98c60b6a-dcc1-4671-b53c-77b7907efc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/material-de-apoyo/artículos?rand=0.6914370415281099' and (text() = 'Artículos' or . = 'Artículos')]</value>
      <webElementGuid>21cd2492-0596-4ce7-b752-9a52a6a2bb45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
