<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Oferta Educativa</name>
   <tag></tag>
   <elementGuidId>20f549b7-1de4-4eea-9110-454da94d68ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.separator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8bae823a-84fa-4c7d-b9c3-e5c555477055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>e9ed8868-5b27-421d-b6a0-32e81ee95acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.5738128355457119</value>
      <webElementGuid>2f6e3c77-0c1c-4186-b9d2-c920171c36c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oferta Educativa</value>
      <webElementGuid>2f118dd5-4c6b-4a53-aefd-52c2c017d3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-376 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>f1de4356-20ee-45ed-b6d2-15d07b574a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      <webElementGuid>fba22a89-59b1-4bfa-ba89-3eb46da02f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Oferta Educativa')]</value>
      <webElementGuid>176b2e1c-9f7f-4f74-a40d-ca23ae337094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::a[2]</value>
      <webElementGuid>6f9b0652-4c93-4540-a70e-3108acdbd4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Agente'])[1]/following::a[3]</value>
      <webElementGuid>c104da7e-e22f-4220-96c8-033c8ab64f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[1]/preceding::a[1]</value>
      <webElementGuid>1ec38ca5-a91c-47b5-b0e1-ae0934dd95ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros de Personas'])[1]/preceding::a[2]</value>
      <webElementGuid>ac280a99-fc71-4315-a779-703b29f52d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oferta Educativa']/parent::*</value>
      <webElementGuid>18018c69-6702-4dc0-994d-1d2f26889e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.5738128355457119')]</value>
      <webElementGuid>c13ec606-6de4-4d8f-ad7f-c7b0972742b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>8d55de45-fca0-499e-9a5b-5037a305fcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.5738128355457119' and (text() = 'Oferta Educativa' or . = 'Oferta Educativa')]</value>
      <webElementGuid>c88cb00d-634d-4aec-bfb4-5c2cedb0bffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
