<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Quines somos</name>
   <tag></tag>
   <elementGuidId>f7351df0-4f35-4c68-834b-2084c2337b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titulo-articulos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo-articulos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c88ce333-db7c-4413-ab8c-2d4ee16b36d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo-articulos</value>
      <webElementGuid>adceb06b-3df2-43eb-86df-4ffae18fe10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¿Quiénes somos?</value>
      <webElementGuid>18828224-5728-4c90-8635-78dbc6b2f346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo-articulos&quot;)</value>
      <webElementGuid>30f77463-504d-4a1a-a2be-cd5e1fc9cd17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo-articulos']</value>
      <webElementGuid>5bd21344-c679-49ea-90e6-5566d7c0d1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros-articulos']/div</value>
      <webElementGuid>2e1ca7b9-a9f2-4809-add3-013a98989db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[2]/following::div[10]</value>
      <webElementGuid>06a0dbd2-146b-41a0-a245-62954b3e6dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oferta Educativa'])[2]/following::div[10]</value>
      <webElementGuid>05dd8049-ca17-4da8-93f3-7116f1ec2c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS GNP'])[3]/preceding::div[1]</value>
      <webElementGuid>d05b5d58-4089-4145-bb73-9bda68db7083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¿Quiénes somos?']/parent::*</value>
      <webElementGuid>79f747ea-4bf0-43e3-bc11-d6401747a060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/article/div/div</value>
      <webElementGuid>f35ce05c-2d24-4dc8-a2e7-5150cb4afa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo-articulos' and (text() = '¿Quiénes somos?' or . = '¿Quiénes somos?')]</value>
      <webElementGuid>ec01b212-5e80-48c1-abcb-ca8a96f0e963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
