<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detalle de Designaciones</name>
   <tag></tag>
   <elementGuidId>93d45905-25ff-4df3-b615-ed82b604447b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-secundario > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='item-secundario']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d6f07fc-29aa-43d0-a521-b40b13b5f3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/mi-plan-de-carrera/mis-avances?vista=det-des</value>
      <webElementGuid>fd3c0079-b8b3-4be9-be8a-01943a218b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detalle de Designaciones</value>
      <webElementGuid>8c37d358-f946-441b-9f4a-87b36c050bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barra-menu&quot;)/span[@id=&quot;item-secundario&quot;]/a[1]</value>
      <webElementGuid>1942468a-7b15-4822-8d45-bbbb9332c4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='item-secundario']/a</value>
      <webElementGuid>8f2c5f26-0345-4eca-879f-39bd41b5303e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Detalle de Designaciones')]</value>
      <webElementGuid>2f7efa5b-dd1b-4daa-852b-338d2e37e47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programas de Capacitación'])[1]/following::a[1]</value>
      <webElementGuid>fe4fca05-753a-474a-855c-03bd9445b92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Agente - biaani.agentec'])[1]/following::a[1]</value>
      <webElementGuid>4bf7ea05-4d63-428e-b8ea-36181fec5391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros Cursos'])[1]/preceding::a[1]</value>
      <webElementGuid>1e7a6397-43d1-4af5-9e28-f0f6a30611ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detalle de Designaciones']/parent::*</value>
      <webElementGuid>361339c8-e48e-49af-92fb-49b97a39a6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/mi-plan-de-carrera/mis-avances?vista=det-des')]</value>
      <webElementGuid>7a342c05-3622-43ff-b057-514e7ad59933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a</value>
      <webElementGuid>676355df-d681-442e-9d86-f97dbe8d66c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/mi-plan-de-carrera/mis-avances?vista=det-des' and (text() = 'Detalle de Designaciones' or . = 'Detalle de Designaciones')]</value>
      <webElementGuid>e752b464-dc18-4387-85ae-9950c0e6369f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
