<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TodosgnpDescuentosEstructura Comercial</name>
   <tag></tag>
   <elementGuidId>a205558c-9856-4e49-b1f5-5c2cfd3b8250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6d3a03b-1769-46f3-98ad-775f1f2ab36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cate</value>
      <webElementGuid>2192529b-a465-42cc-91ee-38adf2eacf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>acddb4e7-e94e-41c8-8bdd-f50f76fb3b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodosgnpDescuentosEstructura Comercial</value>
      <webElementGuid>a8247f79-bc36-426b-a6ac-9335e11d8481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-año&quot;)/select[1]</value>
      <webElementGuid>abb56bc6-13c3-47cf-8baf-66917bb7f18f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cate']</value>
      <webElementGuid>c18ae2b6-0c01-403c-8cc8-733459cbfdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-año']/select</value>
      <webElementGuid>e25785b6-e6cd-415c-b54c-f8d525b8d8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campañas'])[3]/following::select[1]</value>
      <webElementGuid>48a89321-84de-47b5-b281-e0291d43e30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/var/www/html/pru_gnp_portal/modules/mod_bcs_breadcrumbs/helper.php'])[4]/following::select[1]</value>
      <webElementGuid>55709db5-9ee4-4a18-b764-570b161786a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/preceding::select[1]</value>
      <webElementGuid>05a39384-f733-4cb3-affb-1d654b3f8c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8e874fa4-5e6e-435a-a483-47208d85ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cate' and (text() = 'TodosgnpDescuentosEstructura Comercial' or . = 'TodosgnpDescuentosEstructura Comercial')]</value>
      <webElementGuid>e225d770-5642-46b3-a119-ad686b0eadf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
