<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>f91d546a-1e49-480e-8828-a4db4a79c7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cedula']/div[4]/form/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4a6d621e-5196-4458-b5ad-24437b38a4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_cedulas/assets/btn_ingresa-al-curso_inactivo.png</value>
      <webElementGuid>40a91242-ff38-4d1f-80f6-fc3b47297c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>248px</value>
      <webElementGuid>8a152921-1dfe-4ff2-8cd0-e8a57a37ea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300px</value>
      <webElementGuid>82210f34-a8df-4ad6-a92b-c5b2abf77c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cedula&quot;)/div[4]/form[1]/div[1]/div[2]/a[1]/img[1]</value>
      <webElementGuid>ddcdd3d1-3546-40fd-89ec-444de9069523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cedula']/div[4]/form/div/div[2]/a/img</value>
      <webElementGuid>d8f6dfdd-8b13-4173-8d3c-64e5b957006b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_cedulas/assets/btn_ingresa-al-curso_inactivo.png')]</value>
      <webElementGuid>fbb39839-024e-44b1-874a-346521157450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>051f7284-1385-46ea-8e89-0da36cde5927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_cedulas/assets/btn_ingresa-al-curso_inactivo.png']</value>
      <webElementGuid>e53d4ac8-9d4e-455b-8b8b-7ad7eb75ed90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
