<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Videos</name>
   <tag></tag>
   <elementGuidId>eda0277b-e9b4-4218-a224-474a7fea030d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[4]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.item-401 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ee12c6e-c1af-4809-a04c-f96dfe90c165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/material-de-apoyo/videos-de-anuncios?rand=0.35660400468244835</value>
      <webElementGuid>713f0044-0e11-4aa1-8682-eaf4933bec81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>b530cce1-1f37-4689-9ec0-73fef36bea2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-397 deeper parent&quot;]/ul[1]/li[@class=&quot;item-401&quot;]/a[1]</value>
      <webElementGuid>6cebe0ed-8626-46f2-b098-4eb993b06299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[4]/ul/li[4]/a</value>
      <webElementGuid>83670bb1-a2bb-4a7d-9814-ab8bef20646e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Videos')]</value>
      <webElementGuid>e48c055b-6378-425d-8872-f0976f312734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tips de Venta'])[1]/following::a[1]</value>
      <webElementGuid>969ced00-484d-4bee-93c5-c461bab74f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[1]/following::a[2]</value>
      <webElementGuid>011e1acc-b84b-4d79-83a7-8219e49cc741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pláticas y Conferencias'])[1]/preceding::a[1]</value>
      <webElementGuid>a4b5f64d-99db-466c-8a09-907efc183c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apoyo de Ventas'])[1]/preceding::a[2]</value>
      <webElementGuid>45946ae9-29ee-426e-9ac9-6a5eb84ff2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Videos']/parent::*</value>
      <webElementGuid>2192832c-4c1b-42f0-a645-759fa32d2c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/material-de-apoyo/videos-de-anuncios?rand=0.35660400468244835')]</value>
      <webElementGuid>00e3f033-7a0b-4d95-a4b6-e3363dbae938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[4]/a</value>
      <webElementGuid>db25d399-5f1a-4fe1-a42e-efa04ec23ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/material-de-apoyo/videos-de-anuncios?rand=0.35660400468244835' and (text() = 'Videos' or . = 'Videos')]</value>
      <webElementGuid>f4072f8f-e8f3-4a77-b191-f616285e9a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
