<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Videos</name>
   <tag></tag>
   <elementGuidId>1dd27bb6-5134-48df-a187-e904217e3c06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4d9b1bd-f180-4d3e-8095-618c3bf36b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>fb4cca15-db9f-4b24-af07-7df4cf6f7305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Videos</value>
      <webElementGuid>55476b17-06e1-42bf-948f-c561e6c3d20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo&quot;)</value>
      <webElementGuid>ab2cd22d-22f2-435a-929b-a9f16163c154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo']</value>
      <webElementGuid>a0b04567-82f8-4558-bd68-5395b5b548e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros']/div</value>
      <webElementGuid>6276f65a-cb3c-40b6-9bb5-dd2b816cc69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[2]/following::div[3]</value>
      <webElementGuid>75826b2c-0391-4fe1-84ad-1da4dc2f5d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[2]/following::div[3]</value>
      <webElementGuid>b8fead6b-e2a3-4bbc-a5dd-65e981153a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/preceding::div[7]</value>
      <webElementGuid>3c215306-22b6-44e4-9481-c1b3a9ce8ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>4a4929c5-fe54-4854-9e5c-f06cbc4e55f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo' and (text() = 'Videos' or . = 'Videos')]</value>
      <webElementGuid>aef7e32a-8329-4986-8a99-6eeb315800ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
