<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HOME Informate</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1b3ff658-067a-4d8d-8d43-ab8019f8fdf2</testSuiteGuid>
   <testCaseLink>
      <guid>48270ec4-1946-42bf-b459-291f12ed989f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HOME/Informate/Calendario Operaciones</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4614238-401b-43d9-a967-7610146f039c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abcbfd28-7144-45bb-83f8-a16bb71439aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5a44938-e453-4f9e-9fb1-feb3fca4f9d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HOME/Informate/Campañas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e442cfc5-b6bb-4929-a775-588b04bcba98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a1b483-3884-47a5-89be-b5a5ae075647</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67d91447-df62-4407-a670-08c5769646f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HOME/Informate/Circulares (informate)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd11a263-0f15-4342-ae02-9d51412ab142</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ed1659-f409-46bc-b7e5-a42f1ceb8b10</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4f1411e-3c00-4d59-a7b0-3d5e3c37de46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HOME/Informate/GUIA PORTAL IDEAS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b7b4bee-b3d1-4617-9130-98b43dae8eb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adfe1c82-1853-4052-babb-4494ee6a8e2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e707dd7-40bc-4305-a9d7-32acda983703</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HOME/Informate/Notas Informativas</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bacad01b-687e-4923-9ad7-fbf09365971b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f288823-70a6-4a6a-b009-8a91ab28a7f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
