<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HOME Aprende</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>67e82217-ac0a-43ea-b496-6be17d2bfaed</testSuiteGuid>
   <testCaseLink>
      <guid>eefbb038-207b-4d35-ae81-3d1bd87123c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Aprende/Aula Virtual</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a12e183f-040b-4944-a534-305b7e466aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56ff9f67-ee9d-4f47-ac2b-e824f02c6c63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0125528c-38ca-43b8-bd23-e41da3aee817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Aprende/Libros</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7638d1e7-c7e1-456f-bd7e-d4887c95531b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c06d2f14-a627-4512-a7f1-fdf375efc2f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>127a58b5-66ca-47b2-8fff-88bb695fdcf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Aprende/Mis Avances</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a678416c-12a7-4f93-8d80-1c1852831f70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b57f4e7-7005-417c-99a1-5f4eda8bd0d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d3c887e-4571-4c9c-b793-3300971012bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HOME/Aprende/Tu curso de inicio en GNP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f48c9ae-2f33-4b57-8c0a-13676c864e26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b2e9676-a5a8-494f-8ad8-0a9256aedb7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
