<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MP_Atracción y Desarrollo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3309ff46-6d8e-4e01-aa98-6182363bea28</testSuiteGuid>
   <testCaseLink>
      <guid>79c040d6-4462-4f66-8e74-3621b3cfb055</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atracción y Desarrollo/Arranque</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b870e18-d13f-4134-b9e4-cf5d5c57132b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e56520fc-93c2-455f-a2ef-963e123cb27e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a04d5a6d-d1a4-4d67-807f-5c2077e8422f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atracción y Desarrollo/Prácticas de Trabajo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e113e396-4e76-4387-9192-d3ee1b05a63e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d2153d-41de-42e4-a9f3-13ae01ca695c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d2e22f5-46d5-4d44-908a-264b27137cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Atracción y Desarrollo/Reclutamiento</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>033ab877-8dbc-4652-9ce3-fb5adae9b7fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>663431c3-8fa6-4f83-a38a-11d98f007b5a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
