<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MP_Autoestudio</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>97d44ca5-b27c-4df3-89ae-0b47486f7796</testSuiteGuid>
   <testCaseLink>
      <guid>bef00607-f439-4ad4-a037-45b8f6a81641</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Autoestudio/Cédula A</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4fcd022-5d2e-457a-88c7-ea3ecd33b318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3da6dee-63b6-4f29-b0a9-a89dbcf50a1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa87fd8f-ba0f-40ca-a045-08f0dde697ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Autoestudio/Cédula B</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e83ee8a1-9432-48e6-abb5-ffa3468c139d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bbbe37b-1ced-4fc4-a066-994884ef8811</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5efe22fa-fd98-48e0-aced-56337be13369</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Autoestudio/IDEAS en Corto</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7af0513e-4229-49e2-960d-7f9d67e947d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dac7f85-ce86-4ba7-8e67-45b11a223142</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c17d756b-4529-40d0-8479-1c59b9b7e53f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Autoestudio/Microclases</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ed0c89-de4c-4af2-b62e-a9c4debf6a9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0873c31-66ca-47be-95b2-bba3f24e2e75</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
