<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MP_Material de Capacitación</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8fa2abeb-504f-4180-84a0-cba9b6c98b37</testSuiteGuid>
   <testCaseLink>
      <guid>af45999e-6139-4e8e-9708-685541e6b129</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Artículos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cd5ab44-c588-4bc7-ab97-c50b225c219f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37c70c40-cc5e-4c42-86ca-8ba67bc589d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a38e4330-c755-4acc-922f-e8244c0a94d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Pláticas y Conferencias</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a79b395-9f19-47a2-be1b-d6dd5bfad890</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35819af2-c6ea-478d-9417-e6eeccbed27b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>100a2c05-ce37-4efc-9415-aa0262fae54e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Publicaciones IDEAS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1b7f08d-5a20-4d44-97ac-0514faadafa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e391299-6a35-4af9-9784-df2f11e2fdc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08dfc334-9b7b-4088-b44b-8165603ace92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Tips de Venta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b6f0d34-bfcc-4464-ac8b-ba4fec060f7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b90a735-aae1-49da-92f4-237d98edc41c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af2eb69c-3d28-4d00-95e2-9364cac8f7c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Material de Capacitación/Vídeos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32a8022c-a11b-42d8-98f2-f685b5f46c92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ea51084-ca9f-4db8-b482-1d9cca40f1a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
