<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MP_OfertaEducativa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5bf439b3-bf9c-44de-94d6-da1b0d259338</testSuiteGuid>
   <testCaseLink>
      <guid>7e45d568-751e-4aa3-845b-508a769812cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Director de Agencia</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0076b4bc-5095-400f-83d2-c89e409c67d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6f48b84-8a74-4cff-b7dc-12f4a1250391</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a361c75-0f14-4e55-b32d-a9a62bf045f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Gerente de Desarrollo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74c57576-bf61-467d-92e9-f3a0f14915f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b964371-2649-45c4-8a46-246cbf8c1384</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4796a40-7079-4c7a-93ce-a1f2aae67151</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/IDEAS GNP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6130e4b2-fb7d-401e-8fb0-60071282e969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89a1cff9-7546-4a5b-b021-e1fb2e14499b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f126583-f398-46bf-8987-78633be29a18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Plan de Carrera</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f833462-87b6-46c5-a43d-64bacfc93cca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40c47675-f442-40d8-a558-11a5fe1ab005</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14e9861c-32e8-4eef-b116-017bf7a479ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Quienes somos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89eddfe-047d-4acc-9f92-293e15bf6d00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1d03f2-a961-4ace-b15a-49a864b88ffa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e221336a-8089-4f86-a570-ca0e3001a0d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Reglamento</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc56e211-d59b-4476-a293-cf2769a6d4ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c0d08e5-d4d7-4376-bb9f-874069803722</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be90f66f-c894-42db-9ef8-28558bc7be9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Seguro Persona</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb7dc4dd-a1bd-40eb-8214-494ec82450ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d76c6e9-40e3-43f8-9263-7359390a6a2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b482346a-abb4-4302-a513-926cea61ab7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Oferta Educativa/Seguro PyMEs</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5636e098-f126-4ce1-8d35-1e38140a5481</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98afd1ce-ab58-49e5-a316-ca92bc46171e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
