<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MP_Plan de carrera</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b30ccc7d-1577-4951-8c5d-febf5d379039</testSuiteGuid>
   <testCaseLink>
      <guid>608b567a-cba2-4d42-b4f7-d1baae6f6eb8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Mi plan de carrera/Inducción a GNP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>498deccd-a177-4586-8908-5da2a0738df2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c9a6506-f4e6-47af-bcb6-f356750c8364</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cdd1d36-24e4-4558-8dc1-b31545d31f50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Mi plan de carrera/Inducción GMM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9196141a-44e0-49a5-88cf-7b6fe0bc3e3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83894c4c-8cfa-4cf1-b0b3-3bdb91c21d9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59d56de4-8097-4a92-b22f-1668502eabcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Menú Principal/MP_Mi plan de carrera/Material de Capacitación(bueno)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ee0c5fd-7f9b-466b-8e50-63b82833ff8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed4b11f2-8311-4dd9-910e-7de712f15efb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
