<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>50d1b694-1f98-4d99-b490-10f0cb6ca04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3745 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='3745']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0c3b5de-dea7-403b-92dc-d02e4eab7e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_articles/assets/pdfnegro.png</value>
      <webElementGuid>7b5cd575-d84a-4021-8e98-fdaebf4818a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3745&quot;)/img[1]</value>
      <webElementGuid>72ef538d-dc95-4113-a688-2158332714b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='3745']/img</value>
      <webElementGuid>87d80734-0934-4352-a4ee-3b963d388fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_articles/assets/pdfnegro.png')]</value>
      <webElementGuid>05ad8b1d-6e61-49f9-bd9f-329f44c917b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/img</value>
      <webElementGuid>b9b1dce7-e24c-46f0-a95b-a2ebfde27c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_articles/assets/pdfnegro.png']</value>
      <webElementGuid>62145a66-9884-4fec-b591-e033867e9275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
