<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eventos</name>
   <tag></tag>
   <elementGuidId>ff9814f2-9613-43b5-b238-dce80fa4a18d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.item-402 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>261c88af-0c5f-4ccd-a5cc-4598ceaff3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/eventos?rand=0.9249902811546931</value>
      <webElementGuid>39cf02eb-9e82-4dab-b045-dfbb424db202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eventos</value>
      <webElementGuid>27a4d052-c4df-42eb-a90e-4cd06de07079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-402&quot;]/a[1]</value>
      <webElementGuid>f0aa36c5-7f96-4fd5-bf2e-ebc919405021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[7]/a</value>
      <webElementGuid>2f5cf4a5-8153-4329-ad84-25ef82725e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eventos')]</value>
      <webElementGuid>6ea803e8-71f9-4c75-8a22-bcf2a31c5561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ética y Cumplimiento'])[1]/following::a[1]</value>
      <webElementGuid>928bca97-efe4-4aff-80e7-a672d8b0a10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apoyo de Ventas'])[1]/following::a[2]</value>
      <webElementGuid>25ddedd3-7954-4671-8975-d80933f40d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comunicación'])[1]/preceding::a[1]</value>
      <webElementGuid>825a3657-62f0-4afc-93a6-80546b6c7f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campañas'])[1]/preceding::a[2]</value>
      <webElementGuid>b12fabf3-3b79-470e-953f-e0f02677b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eventos']/parent::*</value>
      <webElementGuid>792f841b-37c4-4fd8-95bc-495190d9a163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/eventos?rand=0.9249902811546931')]</value>
      <webElementGuid>b02d2f4c-6b2d-4758-b07d-7ca05a9e99d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>d1043c32-29c2-4748-83ee-4605b4d426b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/eventos?rand=0.9249902811546931' and (text() = 'Eventos' or . = 'Eventos')]</value>
      <webElementGuid>650f2532-50c4-4baf-a121-5d2ad95e1f46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
