<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Autoestudio</name>
   <tag></tag>
   <elementGuidId>90c1bacd-5e03-4b43-890a-5751e4f89443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.item-435.deeper.parent > a.separator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;art-main&quot;]/nav/div/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75ffc448-cd03-424d-96bc-c580e2a0a0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>da6189da-d115-41ee-b2ed-892a199d16e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.06204193019965598</value>
      <webElementGuid>5c073254-ef5b-48be-a12b-1baab9726a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Autoestudio</value>
      <webElementGuid>4a5f88f3-8eb4-44e6-8b97-4c2c001e4745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-435 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>06dbbc46-7382-4dc5-a3d1-0c7284f35079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[5]/a</value>
      <webElementGuid>20768c73-1809-4f07-b55b-32317df0a775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Autoestudio')]</value>
      <webElementGuid>d2dc51cc-689a-4c0a-903f-11e7d6e3dde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prácticas de Trabajo'])[1]/following::a[1]</value>
      <webElementGuid>4ed386a2-de40-4657-8e02-f46158b03f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arranque'])[1]/following::a[2]</value>
      <webElementGuid>6a4f478c-6866-492f-a8e5-f8e58156a9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microclases'])[1]/preceding::a[1]</value>
      <webElementGuid>be7af62c-4406-46a8-997e-c7cc7dda48df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS en Corto'])[1]/preceding::a[2]</value>
      <webElementGuid>6824a692-1718-4c03-9b4b-798c0adf6da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Autoestudio']/parent::*</value>
      <webElementGuid>9e628889-d085-4225-a1d1-b82f93f5e87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.06204193019965598')]</value>
      <webElementGuid>be6368b3-b7f7-4b81-8fb3-3eec71af990c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>1039423b-e727-4e3c-8a4c-5d1ebfb620e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.06204193019965598' and (text() = 'Autoestudio' or . = 'Autoestudio')]</value>
      <webElementGuid>d7ffb356-da90-4064-9731-5145e3de4aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
