<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>28c37bcd-aa2b-444e-ac31-49014d6112f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fecha-profile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fecha-profile > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>118e5cc8-131f-4118-8555-8d2cd0afdf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png</value>
      <webElementGuid>ce9d7e76-9767-4ac1-8b5c-b289db402bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>c08b33ff-85df-4c77-bd83-d361a6328e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>6632fb68-9186-4e9b-bd18-80e73731e50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha-profile&quot;)/img[1]</value>
      <webElementGuid>72d735b9-01e7-4173-8100-f92210aa300c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fecha-profile']/img</value>
      <webElementGuid>67535966-d107-4cd0-956b-e1c01b7b4e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png')]</value>
      <webElementGuid>9f358373-3c4c-419a-8c5c-e3dfa4ffcc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>3b97b946-3b1e-4191-9122-2fceeefebcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com//modules/mod_bcs_plan_carrera/assets/calendar.png']</value>
      <webElementGuid>5740b23b-e51d-4877-a02a-efa9b3bf764d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
