<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cursos</name>
   <tag></tag>
   <elementGuidId>6771271b-bfe5-4d1f-bdf4-7e1cb5c0b958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titulo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82a9be5f-da76-4a3a-b37e-872d809931c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>fe692bce-42f7-454d-9ee4-bc3e12c8dbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cursos</value>
      <webElementGuid>e2d80637-b172-406e-8a92-834649a60711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo&quot;)</value>
      <webElementGuid>5d3c06f9-e5e0-4592-aef4-20153c297b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo']</value>
      <webElementGuid>095fb9e5-f5a3-4aa2-b5ac-11912dac64b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar-wrap']/header/div</value>
      <webElementGuid>4f90bbb2-498c-4a9f-b358-83e73689ad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notas informativas'])[1]/following::div[5]</value>
      <webElementGuid>03769524-4291-4b5f-b906-94f096f5c447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Circulares'])[1]/following::div[5]</value>
      <webElementGuid>429348b6-b1ce-4869-98b5-406818b60873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar Curso:'])[1]/preceding::div[1]</value>
      <webElementGuid>ded16885-63ad-4c26-a6f2-b87fc9c3aa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cursos']/parent::*</value>
      <webElementGuid>6f05b80c-7c9a-46fb-998b-650c8f6781ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/header/div</value>
      <webElementGuid>b7794520-5cc6-420d-82b3-266c8bcc4d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo' and (text() = 'Cursos' or . = 'Cursos')]</value>
      <webElementGuid>44338569-d755-4c56-94e2-5252d1a54035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
