<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Libros</name>
   <tag></tag>
   <elementGuidId>af3c4e82-9c0d-4e39-8340-4ca4de0c0c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#titulo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97f28fdf-a640-4f49-a799-00ffec153631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>0c552737-bb71-4ba8-a703-fd6cdcac890c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libros</value>
      <webElementGuid>a4cceb36-428e-4735-880e-293660b8b6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo&quot;)</value>
      <webElementGuid>d1c3aa97-da96-4761-9c52-9e31c79096e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo']</value>
      <webElementGuid>bcf99e2c-f627-4787-8d8e-159960e13603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros']/div</value>
      <webElementGuid>e22e1f70-b9cb-4b99-ab2b-a8cf18e5f423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[2]/following::div[3]</value>
      <webElementGuid>70f4ab61-5ff5-4cfe-8ff3-ae90947d14ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[2]/following::div[3]</value>
      <webElementGuid>06b38e12-01c6-4531-9651-2cfb214bdc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digitalízate o desaparece'])[1]/preceding::div[8]</value>
      <webElementGuid>a8f6ad85-c309-4d66-8694-5776189f2cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>827598e6-413f-427b-95f3-7ba37590aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo' and (text() = 'Libros' or . = 'Libros')]</value>
      <webElementGuid>ee744c5a-84b9-4eda-a438-11f96fef93e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
