<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Detalle de Cursos</name>
   <tag></tag>
   <elementGuidId>3cf7b46d-620c-4071-942b-f2ed64a45390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#det-age</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='det-age']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f8d486f-544c-4877-b01f-84edac76f07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>det-age</value>
      <webElementGuid>f97fbc0b-fa7a-49bb-82e7-a4a9197945fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detalle de Cursos</value>
      <webElementGuid>4a06ff55-f955-4291-9c74-cf6b2b6ffc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;det-age&quot;)</value>
      <webElementGuid>f9b77a23-b956-45b9-8bb5-b7691b6000e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='det-age']</value>
      <webElementGuid>d7b73b7e-a70d-4400-b574-3c8068bce600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros']/div[4]</value>
      <webElementGuid>67273a30-c148-43d3-939d-7667afecab67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Agente - biaani.agentec'])[1]/following::div[2]</value>
      <webElementGuid>670bb78d-d23e-43ea-a90d-320aea3a8401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Bienvenido!'])[1]/following::div[2]</value>
      <webElementGuid>8d4bf575-e41d-4f63-9e46-1a815b5689c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cursos exclusivos para Agentes conectados en los últimos 2 meses.'])[1]/preceding::div[1]</value>
      <webElementGuid>0d8fbc96-a8e9-446b-aec0-4653964fc507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cursos a los que estás inscrito'])[1]/preceding::div[1]</value>
      <webElementGuid>70e74729-d53f-46df-935e-91ae0b9750df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detalle de Cursos']/parent::*</value>
      <webElementGuid>c8ce6f78-3f3f-44e7-9b4b-7f192e3c5708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]</value>
      <webElementGuid>fb3bd7f5-d817-486d-9c1b-0719951eb8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'det-age' and (text() = 'Detalle de Cursos' or . = 'Detalle de Cursos')]</value>
      <webElementGuid>502dbdc0-c67b-4667-8b65-38f53704ac09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
