<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>956bc972-91fa-4f03-b7f7-860eff9faf2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo GNP&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='image-home-gnp']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>224cb9ef-58ba-44f0-afd4-9ba4969f7abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>b159253a-e95c-4707-bd3f-eaed6e8ffea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>645d3b0a-868a-4a9f-b0f8-1aaac4d1bce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo GNP</value>
      <webElementGuid>d41362e0-ae97-4959-a519-22cf5e663959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/templates/gnp/images/logo-gnp2.png</value>
      <webElementGuid>ef153246-b782-4e76-b7a4-10a3f966ce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image-home-gnp&quot;)/a[1]/img[1]</value>
      <webElementGuid>d9274680-c9ee-4f67-88f6-1d1e0be70ac3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='image-home-gnp']/a/img</value>
      <webElementGuid>366997de-55ae-4d1d-b366-cf434329fb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo GNP']</value>
      <webElementGuid>9ba4e17e-3b7e-44cb-b9a1-1f9aa8680602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f25fb060-7b5f-4b73-9403-5b4f15ebee2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo GNP' and @src = '/templates/gnp/images/logo-gnp2.png']</value>
      <webElementGuid>ac7a8d26-8be7-4c69-b806-d5f1f90bed37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
