<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Libros</name>
   <tag></tag>
   <elementGuidId>d3957e2a-40f9-4514-a09a-05b730865e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.item-446 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[6]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76b56b60-30f8-4455-b403-d454bd91bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/material-de-apoyo/libros?rand=0.8300930506556741</value>
      <webElementGuid>c998346e-3b64-4bc7-a76b-c45e5e0804b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libros</value>
      <webElementGuid>fae3e253-3102-4ad4-ab30-daa34b61d4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-444 deeper parent&quot;]/ul[1]/li[@class=&quot;item-446&quot;]/a[1]</value>
      <webElementGuid>ee19e6d4-8121-4afd-b91c-2bef967ef299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a03fe07d-134e-4269-bf67-94eda54de39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/material-de-apoyo/libros?rand=0.9319869232728235</value>
      <webElementGuid>cab92172-069b-40d4-94f7-d25ccae13855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libros</value>
      <webElementGuid>07c27f1a-e1fe-4a84-a40c-fd8e59e9515b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-444 deeper parent&quot;]/ul[1]/li[@class=&quot;item-446&quot;]/a[1]</value>
      <webElementGuid>067e937b-d92e-4b3c-9bae-1005a46428d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[6]/ul/li[2]/a</value>
      <webElementGuid>57b924a3-696f-4b73-bffd-0a7e47b23137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Libros')]</value>
      <webElementGuid>57e45f7e-2f74-427f-83c4-b4b2f0a8c526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos'])[1]/following::a[1]</value>
      <webElementGuid>28f2df6c-7ae5-424c-af88-2372c9153678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[1]/following::a[2]</value>
      <webElementGuid>ba2b6200-31d3-4187-88c1-b63bb7b358e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tips de Venta'])[1]/preceding::a[1]</value>
      <webElementGuid>bfe95a72-e5f0-409c-b39e-2e521a10d586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::a[2]</value>
      <webElementGuid>d22083d5-ea10-4a47-9a9a-af8f04c5a256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Libros']/parent::*</value>
      <webElementGuid>c7b74d6b-1e1d-4e26-91a2-6eb554b24adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/material-de-apoyo/libros?rand=0.8300930506556741')]</value>
      <webElementGuid>07e6496a-9d42-4318-8ea6-9f4c2b3b907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]/a</value>
      <webElementGuid>ce9711f0-993b-4bb7-aab5-e9415ab1f97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/material-de-apoyo/libros?rand=0.8300930506556741' and (text() = 'Libros' or . = 'Libros')]</value>
      <webElementGuid>85ece61a-585e-4f5c-ab05-356be75a9515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/material-de-apoyo/libros?rand=0.9319869232728235')]</value>
      <webElementGuid>be5ec2a9-c6bd-4622-aa3e-20dfeabd7001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/material-de-apoyo/libros?rand=0.9319869232728235' and (text() = 'Libros' or . = 'Libros')]</value>
      <webElementGuid>0ee2e14c-d191-4eb7-b962-72ac29a762b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
