<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Libros_1</name>
   <tag></tag>
   <elementGuidId>43739e18-0baf-431e-94ac-b19117beb02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.item-446 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[6]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6747ce24-5b3e-40c4-8603-0c42673886b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/material-de-apoyo/libros?rand=0.37979752880322826</value>
      <webElementGuid>fee47c75-3775-41dc-8aab-b151fafb698a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libros</value>
      <webElementGuid>77dbc2e1-4152-489c-9caf-76d5934ce8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-444 deeper parent&quot;]/ul[1]/li[@class=&quot;item-446&quot;]/a[1]</value>
      <webElementGuid>781fcaf1-aba6-47b8-850e-698fb6880029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[6]/ul/li[2]/a</value>
      <webElementGuid>8869300f-bc4c-4677-bd5a-2bc2257ad8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Libros')]</value>
      <webElementGuid>3f730935-7576-41d0-ba63-c392f86dc37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos'])[1]/following::a[1]</value>
      <webElementGuid>75121ae8-5a86-4346-a2ae-7863a3cb578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[1]/following::a[2]</value>
      <webElementGuid>aee80210-446a-4015-9e02-230d7e35ff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tips de Venta'])[1]/preceding::a[1]</value>
      <webElementGuid>d2dc97ee-b029-405c-b915-0ce007d09f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::a[2]</value>
      <webElementGuid>85bdd911-ed89-44ec-98a3-ab3f7b20c57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Libros']/parent::*</value>
      <webElementGuid>0c49ca8f-1fd1-49d9-a768-9dbd4ebf007a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/material-de-apoyo/libros?rand=0.37979752880322826')]</value>
      <webElementGuid>9da9135d-3453-412e-9935-073e4ce92158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]/a</value>
      <webElementGuid>da87ac8b-ad37-4a23-ab7c-1a656e2ab75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/material-de-apoyo/libros?rand=0.37979752880322826' and (text() = 'Libros' or . = 'Libros')]</value>
      <webElementGuid>8c73471f-5e23-4ea9-aa77-110d0da7e4fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
