<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TodosAdministracinHabilidades Profes_6740da</name>
   <tag></tag>
   <elementGuidId>83337a48-9047-4b3a-8a14-8e895d81fee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a21bde38-f5fc-4a0b-9c09-5f42d05107f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cate</value>
      <webElementGuid>883b66df-6694-4186-b01a-493128fd9f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>dc154b0c-dc11-489f-8505-64d65658e81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TodosAdministraciónHabilidades ProfesionalesInnovaciónLiderazgoVentas</value>
      <webElementGuid>0acb3fc8-a5b5-4ab5-b132-3cc87d762952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-año&quot;)/select[1]</value>
      <webElementGuid>4683c8cc-bfc0-40f8-ae3e-d9151d91c9c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cate']</value>
      <webElementGuid>176c80b4-4d93-4d14-a62d-87dbe463342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-año']/select</value>
      <webElementGuid>e18bb60c-ea95-4413-8c85-79e72d2a2c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[3]/following::select[1]</value>
      <webElementGuid>7e4c3bef-141c-43a3-84de-46906300ac7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[2]/following::select[1]</value>
      <webElementGuid>b1ffdc00-932c-4008-a4ae-af574eb8f98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digitalízate o desaparece'])[1]/preceding::select[1]</value>
      <webElementGuid>7a5354c6-c10e-4ce5-aba9-8dfe3af62558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ec358b3f-f505-456d-90b9-cb20b8eaafe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cate' and (text() = 'TodosAdministraciónHabilidades ProfesionalesInnovaciónLiderazgoVentas' or . = 'TodosAdministraciónHabilidades ProfesionalesInnovaciónLiderazgoVentas')]</value>
      <webElementGuid>be873441-db3c-46ad-82d0-55a0b25e25c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
