<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Libros</name>
   <tag></tag>
   <elementGuidId>c5927935-945b-4a62-bf4d-b6e5b9e0112c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='titulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#titulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82ebfb43-9be1-4f91-933f-59377b122c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titulo</value>
      <webElementGuid>35d8ddd6-f5cb-4f93-8144-3fd2ce3a6ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Libros</value>
      <webElementGuid>bfcef2f2-4bdf-46f0-be57-9de7d5c885c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titulo&quot;)</value>
      <webElementGuid>4239fad8-c574-4b77-8431-15e19383fb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='titulo']</value>
      <webElementGuid>1fa45e85-d6cf-406a-acd3-11e081e191e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titulo-filtros']/div</value>
      <webElementGuid>7051c7d8-0efc-4607-8960-30b73960d4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libros'])[2]/following::div[3]</value>
      <webElementGuid>b22988f9-386c-4422-aadd-7340d4be0834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material de Capacitación'])[2]/following::div[3]</value>
      <webElementGuid>aff4a6aa-a69a-4235-bd71-cdf4b80507ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digitalízate o desaparece'])[1]/preceding::div[8]</value>
      <webElementGuid>2bdb1994-c701-468f-abab-ff31775d081c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>d4ab4aeb-b427-4b3e-b49e-dfdd0a083952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'titulo' and (text() = 'Libros' or . = 'Libros')]</value>
      <webElementGuid>fc29c2cb-fcd1-4d0b-b5fa-91b78391e87d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
