<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bsico</name>
   <tag></tag>
   <elementGuidId>27b91149-f986-4a36-9308-ba240e49efe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-first-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-first-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ed72c0c-1a29-48e4-8179-0ec906452eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-first-1</value>
      <webElementGuid>7241fd82-cc04-403c-9b4b-16f8e75595ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Básico
            </value>
      <webElementGuid>d8cc1915-7a58-4a9b-a4ea-f4460a636cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-first-1&quot;)</value>
      <webElementGuid>ee58cf41-d89b-4cbc-a17e-d70358b7a9e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='header-first-1']</value>
      <webElementGuid>41c1342c-b2b7-4123-86d0-bff94f347b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-table']/div[2]</value>
      <webElementGuid>2e15d106-d565-4707-8e4c-ab9d6d0ff622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programa'])[1]/following::div[1]</value>
      <webElementGuid>aaa94934-2904-454e-abb9-155a2c0f452b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguros PyMEs'])[2]/following::div[6]</value>
      <webElementGuid>da80eeb5-a441-4bd8-8dfe-3d08accb1802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermedio'])[1]/preceding::div[1]</value>
      <webElementGuid>370cb3a1-d99e-46b4-be06-6c85f25aaf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avanzado'])[1]/preceding::div[2]</value>
      <webElementGuid>bb4ccb63-afd4-45c5-94eb-d98b09534694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Básico']/parent::*</value>
      <webElementGuid>52ed8e5e-81de-4bb5-8157-d7bbda6b62b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>daa63b76-6c2b-4e97-a6dd-e25685c6541e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'header-first-1' and (text() = '
                Básico
            ' or . = '
                Básico
            ')]</value>
      <webElementGuid>0f5f83f8-7bbf-4acf-8d59-a8a4b5b94b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
