<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>4a69b3c9-842b-4c8a-8c3b-88a5350fb55a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fecha-profile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fecha-profile > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c15647c-a28b-48c5-8005-25565c354dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_plan_carrera/assets/calendar.png</value>
      <webElementGuid>d3c081ac-7d0d-40fc-bc7f-8dc77e97fdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>d46aceaa-645d-4040-9bb9-d37f95c28cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25px</value>
      <webElementGuid>4a0ad84b-6d53-478a-9775-afdc6d160a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fecha-profile&quot;)/img[1]</value>
      <webElementGuid>e811b73a-d76e-431a-a76e-791099785386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fecha-profile']/img</value>
      <webElementGuid>1883b277-4142-44ea-94a4-e2b4c7d060b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_plan_carrera/assets/calendar.png')]</value>
      <webElementGuid>499c5a11-b166-4a82-9318-ce464f48cd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>b5d8bb77-2f82-46fa-a339-4db127502756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_plan_carrera/assets/calendar.png']</value>
      <webElementGuid>75936dec-69f1-47d5-be37-6689d486a24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
