<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Microclases</name>
   <tag></tag>
   <elementGuidId>fc26adbf-c099-47f3-b41b-0454fdd02cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.item-389 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='art-main']/nav/div/ul/li[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99c03566-390a-411c-971d-a7a026ebba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/autoestudio/negocio-individual?rand=0.6467535623443539</value>
      <webElementGuid>9469ee2a-0895-43ef-b899-6894b0ed9b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Microclases</value>
      <webElementGuid>1696028f-d2f9-40a7-b2de-0f39c6a63434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-388 deeper parent&quot;]/ul[1]/li[@class=&quot;item-389&quot;]/a[1]</value>
      <webElementGuid>76a65297-90d5-49d8-a73d-91afc146619f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li[3]/ul/li/a</value>
      <webElementGuid>de3d89e3-d2c0-4c16-adac-59df0a5bc553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Microclases')]</value>
      <webElementGuid>1c1f1558-ba05-422c-8a81-9bb368d0b4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autoestudio'])[1]/following::a[1]</value>
      <webElementGuid>b94fa65f-ef09-4c85-aec2-325427888872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inducción GMM'])[1]/following::a[2]</value>
      <webElementGuid>dd75a876-1086-48d4-9079-2ed683f82bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDEAS en Corto'])[1]/preceding::a[1]</value>
      <webElementGuid>59c7a31d-85cf-4cf2-a0fa-fb1ef3132eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cédula A'])[1]/preceding::a[2]</value>
      <webElementGuid>869a20f0-17e2-4cd1-91d9-1a2fb38e6a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Microclases']/parent::*</value>
      <webElementGuid>12a8e1f2-6b3b-4e93-aa8e-ded486be1768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/autoestudio/negocio-individual?rand=0.6467535623443539')]</value>
      <webElementGuid>b0c23223-d2a8-4a84-90e1-6c77c43fac54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a</value>
      <webElementGuid>8fe87827-a58f-42f2-aca1-d599319e7abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/autoestudio/negocio-individual?rand=0.6467535623443539' and (text() = 'Microclases' or . = 'Microclases')]</value>
      <webElementGuid>2a9f4935-e9c1-4a97-9d95-abb352e6bcb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
