<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Notas informativas_Capturadepantalla201_d4c38e</name>
   <tag></tag>
   <elementGuidId>71692ce3-46c2-4c4b-9064-56b8a14240c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Capturadepantalla20170130alas1017_r1_c3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Capturadepantalla20170130alas1017_r1_c3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a2663ed4-e564-4719-b53d-3236a7446eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png</value>
      <webElementGuid>49511144-6024-4755-865f-9c61f01e27ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>39bd7d00-e154-4a08-ad7b-f44991a50be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>46d91f56-2df4-4742-b420-b959db7bdbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20e32c61-7c2e-498d-9761-17da34486449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Capturadepantalla20170130alas1017_r1_c3</value>
      <webElementGuid>db7bb405-f010-42b5-a9a6-c9f7ab853eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Capturadepantalla20170130alas1017_r1_c3&quot;)</value>
      <webElementGuid>18f14ab1-19e9-43a0-b81b-bf1fc319aaf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Capturadepantalla20170130alas1017_r1_c3']</value>
      <webElementGuid>84ede705-bfc6-48e5-bc60-4e2f1aa72f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcrumbs']/table/tbody/tr[2]/td[3]/a/img</value>
      <webElementGuid>8163bb3d-b802-4208-a779-e41c9187f522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png')]</value>
      <webElementGuid>668b279b-d547-4360-8b1e-966ca8308c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>4a4f13f1-95a9-4d26-a470-6674fa95d53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png' and @id = 'Capturadepantalla20170130alas1017_r1_c3']</value>
      <webElementGuid>d974c750-a147-4144-b3d8-c19f62a61ca3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
