<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Notas informativas_Capturadepantalla201_d4c38e</name>
   <tag></tag>
   <elementGuidId>d174ec72-b43d-43dc-81c9-161b89e2377d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='Capturadepantalla20170130alas1017_r1_c3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Capturadepantalla20170130alas1017_r1_c3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc27fa4c-c880-4159-bd3a-ede191a219d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png</value>
      <webElementGuid>f42aeb36-1747-4856-bc8c-e4fb0d049175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>201</value>
      <webElementGuid>ec9980d6-19b2-4c9a-9dd2-eb9f332d959d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>deeb80ae-d4f5-4b48-bc65-8c483d7fa9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b7c486b-bc7e-449c-b913-d36373a24693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Capturadepantalla20170130alas1017_r1_c3</value>
      <webElementGuid>376f3581-1958-4c55-bc04-f8ef42b60513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Capturadepantalla20170130alas1017_r1_c3&quot;)</value>
      <webElementGuid>924c7f93-746e-44d7-ade7-64d6a986844c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='Capturadepantalla20170130alas1017_r1_c3']</value>
      <webElementGuid>cff02450-49ca-4b8a-a336-1921bf8b39b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcrumbs']/table/tbody/tr[2]/td[3]/a/img</value>
      <webElementGuid>8e8be679-d151-4a26-a397-30d41e147150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png')]</value>
      <webElementGuid>13dd5180-2607-4074-94a4-82334bd9e0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>33c4e690-3c3e-4510-a3db-1ce439e74f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pru-gnp-portalideas.biaani.com/modules/mod_bcs_calendario/assets/bread3.png' and @id = 'Capturadepantalla20170130alas1017_r1_c3']</value>
      <webElementGuid>c14dbdfd-683c-47b4-82e0-66cfc92a9312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
