<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BAJIOCANCELADASFORNEAS NORESTEGUADAL_e6d5e0</name>
   <tag></tag>
   <elementGuidId>401a03e6-bec8-4343-b80e-b58b97202578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;region&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='region']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16c84c7a-a088-4a41-9256-a5daab97767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>f75f27f9-6fba-415a-a2b2-e1b0dcf6b793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>this.form.submit()</value>
      <webElementGuid>d2d7307d-69fe-4d8f-ae6c-03bf3daf6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAJIOCANCELADASFORÁNEAS NORESTEGUADALAJARAMETRO NORTEMETRO PONIENTEMETRO SURMONTERREYNOROESTEOFICINASPACÍFICOPLAZA GNPSMSURESTEVIRTUALES</value>
      <webElementGuid>a5a49e8e-7478-4a3c-b407-dac402332b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titlecal&quot;)/select[1]</value>
      <webElementGuid>340241de-8ed1-4fe7-8de0-832e826d8377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='region']</value>
      <webElementGuid>28ba2f19-84c5-4cd3-9ae5-2422ada1b0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='titlecal']/select</value>
      <webElementGuid>30ff38f6-333b-4404-8f82-1e2331bdeded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>>'])[1]/following::select[1]</value>
      <webElementGuid>c51ca1c6-5743-421a-b9b2-23572e2ac08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;&lt;'])[1]/following::select[1]</value>
      <webElementGuid>cd871e45-a247-417f-8f0c-b629b0943b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Julio'])[1]/preceding::select[1]</value>
      <webElementGuid>1873a8de-2ab3-4330-89cf-2cb2d3b9e164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informes e inscripciones'])[1]/preceding::select[1]</value>
      <webElementGuid>cc7ab263-1989-411b-a79b-39bb8c907b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f83c0a70-029b-451f-8b21-cc5b433788a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'region' and (text() = 'BAJIOCANCELADASFORÁNEAS NORESTEGUADALAJARAMETRO NORTEMETRO PONIENTEMETRO SURMONTERREYNOROESTEOFICINASPACÍFICOPLAZA GNPSMSURESTEVIRTUALES' or . = 'BAJIOCANCELADASFORÁNEAS NORESTEGUADALAJARAMETRO NORTEMETRO PONIENTEMETRO SURMONTERREYNOROESTEOFICINASPACÍFICOPLAZA GNPSMSURESTEVIRTUALES')]</value>
      <webElementGuid>29a19cb1-e149-40a5-9503-91010ea4b234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
